server {
    server_name jumpchainsearch.app www.jumpchainsearch.app;

    location / {
        proxy_pass http://localhost:5248;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support for Blazor
        proxy_set_header Connection "upgrade";
        proxy_buffering off;
        
        # Long timeout for drive scanning operations
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_connect_timeout 600s;
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/jumpchainsearch.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jumpchainsearch.app/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.jumpchainsearch.app) {
        return 301 https://$host$request_uri;
    }

    if ($host = jumpchainsearch.app) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name jumpchainsearch.app www.jumpchainsearch.app;
    return 404;
}

# Staging server block
server {
    server_name dev.jumpchainsearch.app;

    location / {
        proxy_pass http://localhost:5001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection keep-alive;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
        proxy_connect_timeout 600s;
        client_max_body_size 10M;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/dev.jumpchainsearch.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.jumpchainsearch.app/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = dev.jumpchainsearch.app) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    server_name dev.jumpchainsearch.app;
    return 404;
}