// <auto-generated />
using System;
using JumpChainSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JumpChainSearch.Migrations
{
    [DbContext(typeof(JumpChainDbContext))]
    [Migration("20251203210032_AddGoogleDriveFolderIdColumn")]
    partial class AddGoogleDriveFolderIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JumpChainSearch.Models.AdminSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("SessionToken")
                        .IsUnique();

                    b.ToTable("AdminSessions");
                });

            modelBuilder.Entity("JumpChainSearch.Models.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("JumpChainSearch.Models.ApprovedTagRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApprovalSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TagRemovalRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagSuggestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimesApplied")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalVotes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VotesInFavor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalSource");

                    b.HasIndex("GoogleDriveFileId");

                    b.HasIndex("IsActive");

                    b.HasIndex("RuleType");

                    b.HasIndex("TagRemovalRequestId");

                    b.HasIndex("TagSuggestionId");

                    b.HasIndex("GoogleDriveFileId", "TagName", "TagCategory", "RuleType");

                    b.ToTable("ApprovedTagRules");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentPurchasable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CharacterPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryCost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryCost");

                    b.HasIndex("Category", "Name");

                    b.ToTable("DocumentPurchasables");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagCategory");

                    b.HasIndex("TagName");

                    b.HasIndex("JumpDocumentId", "TagName")
                        .IsUnique();

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFolderId")
                        .HasColumnType("TEXT");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDrive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebViewLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleDriveFileId")
                        .IsUnique();

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("JumpDocumentId", "SourceDrive");

                    b.ToTable("DocumentUrls");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentViewCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<int>("UniqueViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JumpDocumentId")
                        .IsUnique();

                    b.ToTable("DocumentViewCounts");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DriveConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentDriveName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAuthMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveId")
                        .IsUnique();

                    b.HasIndex("DriveName");

                    b.ToTable("DriveConfigurations");
                });

            modelBuilder.Entity("JumpChainSearch.Models.FolderConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAutoDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentDriveId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredAuthMethod")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderId")
                        .IsUnique();

                    b.HasIndex("FolderPath");

                    b.HasIndex("ParentDriveId");

                    b.HasIndex("ParentDriveId", "FolderName");

                    b.ToTable("FolderConfigurations");
                });

            modelBuilder.Entity("JumpChainSearch.Models.JumpDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractionMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFolderId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasThumbnail")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("OcrQuality")
                        .HasColumnType("REAL");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDrive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TextLastEditedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextLastEditedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TextNeedsReview")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TextReviewFlaggedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextReviewFlaggedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebViewLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolderPath");

                    b.HasIndex("GoogleDriveFileId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("SourceDrive", "Name");

                    b.ToTable("JumpDocuments");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildTagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentTagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildTagName");

                    b.HasIndex("ParentTagName");

                    b.HasIndex("ParentTagName", "ChildTagName")
                        .IsUnique();

                    b.ToTable("TagHierarchies");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagRemovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTagId");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("JumpDocumentId", "TagName", "TagCategory");

                    b.ToTable("TagRemovalRequests");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestedByUserId");

                    b.HasIndex("JumpDocumentId", "TagName", "TagCategory");

                    b.ToTable("TagSuggestions");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInFavor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagRemovalRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagSuggestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TagRemovalRequestId");

                    b.HasIndex("TagSuggestionId");

                    b.HasIndex("UserId", "TagRemovalRequestId")
                        .IsUnique();

                    b.HasIndex("UserId", "TagSuggestionId")
                        .IsUnique();

                    b.ToTable("TagVotes");
                });

            modelBuilder.Entity("JumpChainSearch.Models.UserTagOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "JumpDocumentId", "TagName", "TagCategory")
                        .IsUnique();

                    b.ToTable("UserTagOverrides");
                });

            modelBuilder.Entity("JumpChainSearch.Models.VotingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoApplyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumVotesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumVotesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("PopularityScaleFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredAgreementPercentage")
                        .HasColumnType("REAL");

                    b.Property<bool>("ScaleByPopularity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VoteDecayRatePerDay")
                        .HasColumnType("REAL");

                    b.Property<int>("VoteDecayStartDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VotingConfigurations");
                });

            modelBuilder.Entity("JumpChainSearch.Models.AdminSession", b =>
                {
                    b.HasOne("JumpChainSearch.Models.AdminUser", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("JumpChainSearch.Models.ApprovedTagRule", b =>
                {
                    b.HasOne("JumpChainSearch.Models.TagRemovalRequest", "TagRemovalRequest")
                        .WithMany()
                        .HasForeignKey("TagRemovalRequestId");

                    b.HasOne("JumpChainSearch.Models.TagSuggestion", "TagSuggestion")
                        .WithMany()
                        .HasForeignKey("TagSuggestionId");

                    b.Navigation("TagRemovalRequest");

                    b.Navigation("TagSuggestion");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentPurchasable", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Purchasables")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentTag", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Tags")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentUrl", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Urls")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentViewCount", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.FolderConfiguration", b =>
                {
                    b.HasOne("JumpChainSearch.Models.DriveConfiguration", "ParentDrive")
                        .WithMany()
                        .HasForeignKey("ParentDriveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentDrive");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagRemovalRequest", b =>
                {
                    b.HasOne("JumpChainSearch.Models.DocumentTag", "DocumentTag")
                        .WithMany()
                        .HasForeignKey("DocumentTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTag");

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagSuggestion", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagVote", b =>
                {
                    b.HasOne("JumpChainSearch.Models.TagRemovalRequest", "TagRemovalRequest")
                        .WithMany("Votes")
                        .HasForeignKey("TagRemovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JumpChainSearch.Models.TagSuggestion", "TagSuggestion")
                        .WithMany("Votes")
                        .HasForeignKey("TagSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TagRemovalRequest");

                    b.Navigation("TagSuggestion");
                });

            modelBuilder.Entity("JumpChainSearch.Models.UserTagOverride", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.JumpDocument", b =>
                {
                    b.Navigation("Purchasables");

                    b.Navigation("Tags");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagRemovalRequest", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagSuggestion", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
