// <auto-generated />
using System;
using JumpChainSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JumpChainSearch.Migrations
{
    [DbContext(typeof(JumpChainDbContext))]
    [Migration("20251108234651_MakeDocumentTagIdNullable")]
    partial class MakeDocumentTagIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JumpChainSearch.Models.DocumentPurchasable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CharacterPosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostsJson")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrimaryCost")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("Name");

                    b.HasIndex("PrimaryCost");

                    b.HasIndex("Category", "Name");

                    b.ToTable("DocumentPurchasables");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagCategory");

                    b.HasIndex("TagName");

                    b.HasIndex("JumpDocumentId", "TagName")
                        .IsUnique();

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDownloadUrl")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublicUrl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDrive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebViewLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleDriveFileId")
                        .IsUnique();

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("JumpDocumentId", "SourceDrive");

                    b.ToTable("DocumentUrls");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentViewCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastViewed")
                        .HasColumnType("TEXT");

                    b.Property<int>("UniqueViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JumpDocumentId")
                        .IsUnique();

                    b.ToTable("DocumentViewCounts");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DriveConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveId")
                        .IsUnique();

                    b.HasIndex("DriveName");

                    b.ToTable("DriveConfigurations");
                });

            modelBuilder.Entity("JumpChainSearch.Models.JumpDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractionMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasThumbnail")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDrive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebViewLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleDriveFileId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("SourceDrive", "Name");

                    b.ToTable("JumpDocuments");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagRemovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DocumentTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTagId");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("JumpDocumentId", "TagName", "TagCategory");

                    b.ToTable("TagRemovalRequests");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AppliedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedByUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("Status");

                    b.HasIndex("SuggestedByUserId");

                    b.HasIndex("JumpDocumentId", "TagName", "TagCategory");

                    b.ToTable("TagSuggestions");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsInFavor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagRemovalRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagSuggestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TagRemovalRequestId");

                    b.HasIndex("TagSuggestionId");

                    b.HasIndex("UserId", "TagRemovalRequestId")
                        .IsUnique();

                    b.HasIndex("UserId", "TagSuggestionId")
                        .IsUnique();

                    b.ToTable("TagVotes");
                });

            modelBuilder.Entity("JumpChainSearch.Models.UserTagOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "JumpDocumentId", "TagName", "TagCategory")
                        .IsUnique();

                    b.ToTable("UserTagOverrides");
                });

            modelBuilder.Entity("JumpChainSearch.Models.VotingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoApplyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumVotesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumVotesRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("PopularityScaleFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("RequiredAgreementPercentage")
                        .HasColumnType("REAL");

                    b.Property<bool>("ScaleByPopularity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VoteDecayRatePerDay")
                        .HasColumnType("REAL");

                    b.Property<int>("VoteDecayStartDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("VotingConfigurations");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentPurchasable", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Purchasables")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentTag", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Tags")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentUrl", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Urls")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentViewCount", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagRemovalRequest", b =>
                {
                    b.HasOne("JumpChainSearch.Models.DocumentTag", "DocumentTag")
                        .WithMany()
                        .HasForeignKey("DocumentTagId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentTag");

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagSuggestion", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagVote", b =>
                {
                    b.HasOne("JumpChainSearch.Models.TagRemovalRequest", "TagRemovalRequest")
                        .WithMany("Votes")
                        .HasForeignKey("TagRemovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("JumpChainSearch.Models.TagSuggestion", "TagSuggestion")
                        .WithMany("Votes")
                        .HasForeignKey("TagSuggestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("TagRemovalRequest");

                    b.Navigation("TagSuggestion");
                });

            modelBuilder.Entity("JumpChainSearch.Models.UserTagOverride", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany()
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.JumpDocument", b =>
                {
                    b.Navigation("Purchasables");

                    b.Navigation("Tags");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagRemovalRequest", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("JumpChainSearch.Models.TagSuggestion", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
