// <auto-generated />
using System;
using JumpChainSearch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JumpChainSearch.Migrations
{
    [DbContext(typeof(JumpChainDbContext))]
    [Migration("20251024203637_AddDocumentUrls")]
    partial class AddDocumentUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("JumpChainSearch.Models.DocumentTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TagCategory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TagCategory");

                    b.HasIndex("TagName");

                    b.HasIndex("JumpDocumentId", "TagName")
                        .IsUnique();

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentUrl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("JumpDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDrive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebViewLink")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleDriveFileId")
                        .IsUnique();

                    b.HasIndex("JumpDocumentId");

                    b.HasIndex("JumpDocumentId", "SourceDrive");

                    b.ToTable("DocumentUrls");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DriveConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriveId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastScanTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DriveId")
                        .IsUnique();

                    b.HasIndex("DriveName");

                    b.ToTable("DriveConfigurations");
                });

            modelBuilder.Entity("JumpChainSearch.Models.JumpDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DownloadLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleDriveFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastScanned")
                        .HasColumnType("TEXT");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceDrive")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebViewLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleDriveFileId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("SourceDrive", "Name");

                    b.ToTable("JumpDocuments");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentTag", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Tags")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.DocumentUrl", b =>
                {
                    b.HasOne("JumpChainSearch.Models.JumpDocument", "JumpDocument")
                        .WithMany("Urls")
                        .HasForeignKey("JumpDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JumpDocument");
                });

            modelBuilder.Entity("JumpChainSearch.Models.JumpDocument", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Urls");
                });
#pragma warning restore 612, 618
        }
    }
}
